CREATE TABLE [dbo].[TransportSaleAnnounces]
(
		[Id]				INT NOT NULL IDENTITY(1, 1),
		[IsDeleted]			BIT NOT NULL DEFAULT(0),
		[CreatedAt]			DateTime NULL,
		[UpdatedAt]			DateTime NULL,
		[DeletedAt]			DateTime NULL,
		[AdNumber]			BIGINT NOT NULL,
		[Year]				DateTime NOT NULL,
		[Mileage]			INT NOT NULL,
		[PriceInDollars]	FLOAT	NOT NULL,
		[SourceLink]		NVARCHAR(2048) NOT NULL,
		[PreviewImageLink]	NVARCHAR(1024) NOT NULL,
		[UpdateOfferTime]	DateTime NOT NULL,
		[Description]		NVARCHAR(2048) NULL,
		[EngineVolumetric]	FLOAT NOT NULL,
		[CityId]			INT NOT NULL,
		[ModelId]			INT NULL,
		[BrandId]			INT NULL,
		[BodyType]			NVARCHAR(32),
		[DriveUnit]			NVARCHAR(32),
		[TransmissionType]	NVARCHAR(32),
		[FuelType]			NVARCHAR(32),
		[VehicleType]		NVARCHAR(32),
		[SourceProvider]	NVARCHAR(32),
		CONSTRAINT	[PK_TransportSaleAnnounces]	PRIMARY KEY CLUSTERED ([Id] ASC),
		CONSTRAINT	[FK_TransportSaleAnnounces_BranId] FOREIGN KEY ([BrandId])	REFERENCES [dbo].[TransportBrands] ([Id]),
		CONSTRAINT	[FK_TransportSaleAnnounces_ModelId] FOREIGN KEY ([ModelId])	REFERENCES [dbo].[TransportModels] ([Id]),
)
